/**
 * Self-hosted font <head> tags. The woff2 files and css/fonts.css are
 * generated by scripts/build_fonts.js as an exact mirror of Google Fonts —
 * see that script before changing anything here.
 *
 * Serving these from our own origin removes two cross-origin handshakes
 * (fonts.googleapis.com then fonts.gstatic.com) that previously had to
 * complete in series before any text could paint.
 */
const FONTS_HREF = '/css/fonts.css?v=1';

/** Latin faces are needed on every page, so start them at HTML parse time. */
const PRELOADED_FONTS = [
  '/assets/fonts/plus-jakarta-sans-latin.woff2',
  '/assets/fonts/instrument-serif-latin.woff2'
];

function renderFontPreloads() {
  return PRELOADED_FONTS.map(
    (href) => '<link rel="preload" href="' + href + '" as="font" type="font/woff2" crossorigin>'
  );
}

function renderFontLinks() {
  return renderFontPreloads().concat('<link rel="stylesheet" href="' + FONTS_HREF + '">');
}

/**
 * Latin @font-face rules inlined into critical CSS so preloaded woff2 files
 * can apply on first paint. Discrete weights are required (same reason as
 * css/fonts.css): 650/800 must keep snapping to 700.
 */
const LATIN_RANGE =
  'U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD';

function latinFace(family, style, weight, file) {
  return (
    "@font-face{font-family:'" +
    family +
    "';font-style:" +
    style +
    ';font-weight:' +
    weight +
    ';font-display:swap;src:url(' +
    file +
    ') format("woff2");unicode-range:' +
    LATIN_RANGE +
    '}'
  );
}

function renderLatinFontFaces() {
  const jakarta = '/assets/fonts/plus-jakarta-sans-latin.woff2';
  return (
    latinFace('Instrument Serif', 'normal', 400, '/assets/fonts/instrument-serif-latin.woff2') +
    [300, 400, 500, 600, 700].map((w) => latinFace('Plus Jakarta Sans', 'normal', w, jakarta)).join('')
  );
}

module.exports = {
  FONTS_HREF,
  PRELOADED_FONTS,
  renderFontPreloads,
  renderFontLinks,
  renderLatinFontFaces
};
