/**
 * Self-hosted font <head> tags. The woff2 files and css/fonts.css are
 * generated by scripts/build_fonts.js as an exact mirror of Google Fonts —
 * see that script before changing anything here.
 *
 * Serving these from our own origin removes two cross-origin handshakes
 * (fonts.googleapis.com then fonts.gstatic.com) that previously had to
 * complete in series before any text could paint.
 */
const FONTS_HREF = '/css/fonts.css?v=1';

/** Latin faces are needed on every page, so start them at HTML parse time. */
const PRELOADED_FONTS = [
  '/assets/fonts/plus-jakarta-sans-latin.woff2',
  '/assets/fonts/instrument-serif-latin.woff2'
];

function renderFontPreloads() {
  return PRELOADED_FONTS.map(
    (href) => '<link rel="preload" href="' + href + '" as="font" type="font/woff2" crossorigin>'
  );
}

function renderFontLinks() {
  return renderFontPreloads().concat('<link rel="stylesheet" href="' + FONTS_HREF + '">');
}

module.exports = { FONTS_HREF, PRELOADED_FONTS, renderFontPreloads, renderFontLinks };
